ISSUE-16 - Remove cargo core usage:
rust-secure-code/cargo-geiger pull request #138
Opened 2020-11-12 18:27 UTC by jmcconnell26

* Remove cargo core usage from scan module
* Remove cargo core usage from traversal module
* Remove cargo core usage from format module
* Remove cargo core usage from scan module
* Refactor krates_utils into separate modules

Signed-off-by: joshmc <josh-mcc@tiscali.co.uk>

2020-11-12 18:32 UTC, jmcconnell26 commented
Working through pulling out more of the cargo::core usage + a small refactoring of the krates_utils into sub modules.

2020-11-14 08:11 UTC, anderejd requested changes
Splitting up the krates_utils module looks great.

2020-11-14 08:11 UTC, anderejd commented on cargo-geiger/src/scan/forbid/table.rs
> +    .unwrap(); // FIXME*/
Delete this?

2020-11-14 09:20 UTC, jmcconnell26 commented on cargo-geiger/src/format/display.rs
> +        let krates = Builder::new()
Good shout! Have updated the usages

2020-11-14 09:44 UTC, merged